#+TITLE: NixOS on the HoneyComb / ClearFog LX2k

* Overview

This is the minimal viable configuration: vendor bootloader and NixOS
image with vendor kernel but buildable with Nix.

* Usage

To boot this configuration, you require a microSD card for uboot, and
USB (or similar) storage for NixOS. This is required because I haven't
yet written an image expression that combines the firmware and the OS
in one image.

** Build and write the sdImage to USB

#+BEGIN_SRC sh
  # Build the isoImage
  nix-build release.nix -A isoImage -o isoImage

  # Write to storage
  cat isoImage/iso-image/*.img > /dev/$usb
#+END_SRC

** Build and write the bootloader to microSD

#+BEGIN_SRC sh
  # Build the uboot image
  nix-build release.nix -A uefi -o uefi.img

  # Write to microSD storage
  cat uefi.img > /dev/$microSD
#+END_SRC

The default memory speed is 3200mhz. If your memory is slower, you
will need to specify a compatible speed with:
#+BEGIN_SRC sh
  # Build the uboot image
  nix-build release.nix -A ubootImage -o ubootImage --arg ddrSpeed 2600
#+END_SRC
** Insert both images and boot

* Notes

*** make menuconfig

Requires some dependencies:

#+BEGIN_SRC sh
  nix-shell -E 'with (import <nixpkgs> {}); stdenv.mkDerivation { name = "fake"; nativeBuildInputs = [ ncurses pkgconfig bison flex ]; }'

  export NIX_CFLAGS_LINK=$(pkg-config --libs ncurses)
#+END_SRC

* Future work

** TODO Improve self-hosting

Determine which of =boot.kernelParams= are important and move them to
a module that can be included by installed systems.

Why is 2gb of memory allocated to huge pages?

* LICENSE

This repo is a port of [[https://github.com/SolidRun/lx2160a_build][Solidrun/lx2160a_build]], and has a copy of the
patches from that repository, it is subject to the same
conditions. Anything original to this repository is available under
the same conditions as nixpkgs for ease of upstreaming.
